# Generated by Django 4.0.2 on 2022-03-02 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_recomment_create_at_recomment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
